### ISSUE TITLE
Integrate the m2m2 lidar into sensors package

### ISSUE THREAD

**Issue by DingoOz** [ROAR-QUTRC/perseus-v2#24]
Using the newly developed test code as a base, we need to integrate the m2m2 into the sensors package:  https://github.com/DingoOz/m2m2_test

Since the m2m2 uses port 1445 and nothing else does it might improve resiliency to have code that monitors which ip address has port 1445 open and selects the ip address that way. Or at least have a tool that can find the ip address based on the port so as to have a backup if static IP address fails.

**Comment by RandomSpaceship** [comment]
I'm not a huge fan of running a port scanner full-time just to detect the lidar, and that's also not bulletproof (plus it's quite expensive) - and if we do have to use it, I'd rather it be streamlined and manual than automatic. A good option (if it supports it) would be to do lookup based on either its hostname or mDNS.
